{"uuid": "2c14091e-3b11-49d7-8410-5e78d72adf80", "children": ["05732b76-9da3-4d72-ad35-902ee503c5eb", "9253ff8c-bf93-4579-ba3d-96c67d6fc11d", "60f661aa-2243-45d7-af33-c673168b03e5", "c98e8490-04f5-428d-a27d-2ded6c52b653", "dfe9ba78-c929-4ccf-88c4-1b0ec5b777a1", "d2ca7814-7819-49b5-8b04-17f87e18d04f", "93ce75f4-038c-4d00-8114-af9c93af6694"], "befores": [{"name": "login_init", "status": "broken", "statusDetails": {"message": "NameError: name 'os' is not defined\n", "trace": "  File \"E:\\install\\python3.10\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\install\\python3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\install\\python3.10\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\install\\DeliverySystem1028\\testCase\\conftest.py\", line 21, in login_init\n    token = Login().login(NAME_PWD, get_token=True)\n  File \"E:\\install\\DeliverySystem1028\\common\\baseApi.py\", line 24, in __init__\n    self.data = get_yml_data(os.path.join(config_path,'apiPathConfig.yml'))[self.__class__.__name__]  # 怎么取？\n"}, "start": 1669971901453, "stop": 1669971901454}], "start": 1669971901453, "stop": 1669971902015}